// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// process_distribute
NumericVector process_distribute(const NumericMatrix& s, const IntegerVector& isnum, const CharacterVector& tid, const NumericVector& weight, const List& map);
RcppExport SEXP _redistribute_process_distribute(SEXP sSEXP, SEXP isnumSEXP, SEXP tidSEXP, SEXP weightSEXP, SEXP mapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type isnum(isnumSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type tid(tidSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< const List& >::type map(mapSEXP);
    rcpp_result_gen = Rcpp::wrap(process_distribute(s, isnum, tid, weight, map));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_redistribute_process_distribute", (DL_FUNC) &_redistribute_process_distribute, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_redistribute(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
