# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

process_distribute <- function(s, isnum, tid, weight, map) {
    .Call(`_redistribute_process_distribute`, s, isnum, tid, weight, map)
}

