# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generate_individuals <- function(region, head_income, size, renting, space, n_neighbors, range, race_rates) {
    .Call(`_redistribute_generate_individuals`, region, head_income, size, renting, space, n_neighbors, range, race_rates)
}

process_distribute <- function(s, method, tid, weight, map, agg, balance) {
    .Call(`_redistribute_process_distribute`, s, method, tid, weight, map, agg, balance)
}

